# Site settings
author: Cyr Edwin
title: Why did you decide to study Software Engineering?
header-img: img/home-bg.png
email: edmundopierre@yahoo.com
copyright_name: Cyr Edwin
description: > # this means to ignore newlines until "baseurl:"
  Software Engineering
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  ekemi

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
